-- ============================================================================
-- Expense Tracker — a standalone general expense/balance ledger, independent of
-- the gold-trading books. Each row is a Received (credit) or Expense (debit);
-- the running balance is computed, not stored.
-- Reads/writes go through server-side API routes (service_role bypasses RLS);
-- RLS is enabled with no policies so nothing is readable by anon/authenticated.
-- Run in Supabase → SQL Editor on each environment.
-- ============================================================================

create table if not exists gls.expenses (
  id          bigint generated by default as identity primary key,
  date        date not null,
  description text not null default '',
  job_id      text,
  received    numeric(14,2) not null default 0,
  expense     numeric(14,2) not null default 0,
  created_by  integer,
  created_at  timestamptz not null default now()
);

alter table gls.expenses enable row level security;

-- Running balance in chronological order (date, then insertion id).
create or replace view gls.expenses_balance as
  select
    e.*,
    sum(e.received - e.expense) over (
      order by e.date, e.id
      rows between unbounded preceding and current row
    ) as balance
  from gls.expenses e;

-- Totals for the header cards.
create or replace function gls.expense_summary()
returns table(total_received numeric, total_expense numeric, balance numeric)
language sql stable
as $$
  select
    coalesce(sum(received), 0),
    coalesce(sum(expense), 0),
    coalesce(sum(received) - sum(expense), 0)
  from gls.expenses;
$$;

grant select on gls.expenses_balance to service_role;
grant execute on function gls.expense_summary() to service_role;
